>P1;WHAT IF-Soup
 
 DITEERLHYQVGQRALIQAMQISAMPELVEAVQKRDLARIKALIDPMRSFSDATYITVGD
 ASGQRLYHVNPDEIGKSMEGGDSDEALINAKSYVSVRKGSLGSSLRGKSPIQDATGKVIG
 IVSVGYTIEQLENYEKLLEDSLTEITALSIEGREAEHNPVVMVHGIGGASFNFAGIKSYL
 VSQGWSRDKLYAVDFWDKTGTNYNNGPVLSRFVQKVLDETGAKKVDIVAHSMGGANTLYY
 IKNLDGGNKVANVVTLGGANRLTTGKALPGTDPNQKILYTSIYSSADMIVMNYLSRLDGA
 RNVQIHGVGHIGLLYSSQVNSLIKEGLNGGGQNTN*                        
